version: '3.2'

services:
  watermelon-online:
    build: '.'
    image: nponline/watermelon:latest
    container_name: watermelon-online
    ports:
      - '8093:8093'
    volumes:
    - ./data:/data


  watermelon-mongo-db:
    image: mongo:4.0.6
    command: mongod --port 27020
    ports:
      - '27020:27020'
    container_name: watermelon-mongo-db
    volumes:
    - ./mongodata:/mongodata
