version: '3.2'

services:
  watermelon-online:
    build: '.'
    image: nponline/watermelon:latest
    container_name: watermelon-online
    volumes:
    - ./data:/data
    environment:
        VIRTUAL_HOST: watermelon.naturalproducts.net
        VIRTUAL_PORT: 8093
        LETSENCRYPT_HOST: watermelon.naturalproducts.net
        LETSENCRYPT_EMAIL: maria.ssorokina@gmail.com


  watermelon-mongo-db:
    image: mongo:4.0.6
    command: mongod --port 27020
    ports:
      - '27020:27020'
    container_name: watermelon-mongo-db
    volumes:
    - ./mongodata:/mongodata


networks:
  default:
    external:
      name: nginx-proxy
